name: "Guacamole"
description: "Apache Guacamole is a clientless remote desktop gateway. It supports standard protocols like VNC, RDP, and SSH."
version: "1.4.0"
slug: "haguacamole"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
ports:
  8080/tcp: 8080
image: abesnier/guacamole:1.4.0
  